#!/usr/bin/python

def get_number_of_pattern_occurence(pattern, genome):
    count = 0
    pos = 0
    while pos < len(genome) - len(pattern):
        if genome[pos: pos + len(pattern)] == pattern:
            count += 1
        pos += 1
    return count

if __name__ == "__main__":
    pattern = 'GAGGTAAGA'
    genome = 'GTCCGAGGTAAAAGTTGTGAGGTAATGTCATGAAGAGGTAAGGATATCTTATTGAGGTAACGAGGAGGTAAGAGGTAACGCGCGGAGGTAAACACTGAGGTAAGTTTGAGGTAACTCGAGGTAAGAGGTAAGAGGTAAGTTTTGCAAAGCGGGAGGTAATGAGGTAATAGGGAGAGGTAATGGGAGGTAATAGAGGTAATGGTGAGGTAAAGAGGTAAGAGGTAAGAGGTAATGTTGAGGTAAAAGACCTCGAGGTAACGGGCTCTTACGCTGAGGTAAGCGAGGTAATCGGTGAGGTAAGGAGGTAAGGAGGTAAGAAGAGGTAATGGAGGTAAAGAGGTAAGAGAGGTAAGGTGAGGTAACTGAGGTAAATAGAGGTAAAAGTAACGAGGTAATGAGGTAAACTAGAGGTAAAAGGCCTGAGGGAGGTAACGAGGTAATAGAGGTAAGAGGTAACGAGGTAACCTGGCCTTTGCAAGTGAGGTGAGGTAATCTGAGGTAAGAGAGGTAACGAGGTAAGAGGTAAAGCTAAGGGCGAGGTAAGGTTGTCGAGGTAACTTTGAGGTAATAGAGGTAAGGAGGTAATTGGGAGGTAAGAGGTAAAGGAGGTGAGGTAAGAGGTAAGAGGTAAGGAGGTAATGAGGTAACGATTCTACATCCACAGAGGTAACGAGGTAAGAGGTAAGAGGTAAGGAAGAGGTAAGGGAGGTAATGAGGTAAGAGGTAATTGAGGTAACGAGGTAAGAGGTAACGGACTGAGGTAAGTTTGAGGTAATCAGCAACGAGGTAAGAGGTAACGTTTAGGGAGGTAATGAGGTAAGGAGGTAAACTGAAGAGGTAAGGAGGTAAATTGAGGTAAGAGGTAAGAGGTAAACGTAAGGAGGTAACGAGGTAACCTGTGATGAGAGGTAAGAGGTAATTTGGAGGTAAGGGCCACCGAGGTAATTAAGAGGTAACTAGAGGTAAGGAGGTAAGTGAGGTAAGAGGTAAGCGAGGTAAGAGGTAA'
    count = get_number_of_pattern_occurence(pattern, genome)
    print(count)


