#!/usr/bin/python

""" Link: http://rosalind.info/problems/mrna/"""

PROTEIN_TRANSLATION = {'A': 4, 'C': 2, 'D': 2, 'E': 2, 'F': 2, 
                       'G': 4, 'H': 2, 'I': 3, 'K': 2, 'L': 6,
                       'M': 1, 'N': 2, 'P': 4, 'Q': 2, 'R': 6,
                       'S': 6, 'T': 4, 'V': 4, 'W': 1, 'Y': 2,
                       'Stop': 3}

def getNumberRNAStrings(protein):
    total = PROTEIN_TRANSLATION['Stop']
    for char in protein:
        total *= PROTEIN_TRANSLATION[char]
    return total % 1000000

if __name__ == "__main__":
    protein = 'MKIAWLSPVAPMAAWMKECGVYDIWLWHEMTAFGEGCETWETQHYVPQVWTDNHQGYCSYATDWAGMNHAPPCPRRKPSVKEGPPAAWVVPGWEAVISFDIHPGYPLGNQYAAEEASVFVMMVPQRCVAGPWYKWIMFFIETKSKCISIKMDWWNCNKLAGSKHTTDHHSFWICCSAVKMGLDKRHQWWMPKVQGKYYWGHAAENYEFNNAYSHSHHPGNCQNQRVHANYDSMRYPQQDYCHNRIPFLWDKNHEVNWKLEGGFITGPWTFWSKIIHQKMYNAHTKEHWGAGRQTNWAWYHQCAMWWTWFSAYIDAPFDRGLRDKEQMEGARQVQTYKMPARNYTMTQTPSKAVVKTALCKKLFQCEDFVFGMGCTMVVSWQSITAVYMLPEKVYTAYPLGWVTYMQKSPDAGQIWLYGVQCGLKDREGYAMQAYMHVVNRTGKSHCMRRCVKNTNCPIICYQGGTGCEYAQIQRVVPEMLYNHATLGQDVTIISKYNGYYTSRLTTYWLDDGHKCMWTRRYFFNRFFSCMIIRLKNWCKSAMWVEHHMHDPSGNEPPEAVHEWRHTTPQQFHTIVPKNFNWEESVTNAGPYNKVNAWQRACRWSSMYHFNYGNMEIIHQHKRHRFYSVLMETMQYLPYKKRPQMTKVHMEWAWWFFISKKYFCPCQEQVNAAPYDANIHGSNKMHQCMCMGDWFLGWFNTSLWFDFQACGNSVKNTRLNEDFKHMLKAGECVYRLDQGPKTMFEIIHLCGQGVNRCLRWCPNWMCMWCWNYYVRSLVCVFDKIFLLVQMVLIHCQYDNFDQKHMGTNQHERQTNFLTWVTFYKSLYNFWKTDQIWHPINCTQKKHVYEIHHDPGLFVQICPNSHSFVQFNVRHSTFIMKMLGLWIDGSDQLEKGRYFDFLCHSNCVIPHSSTHSKYKFQAVLVFCRGINAMFDNTHDTPVSPIASKFIHRSYKMGERAMCYLMCPSRTFGVWSGKFPSHEPSPMKYIWGMASMKAHEY' 
    numStrings = getNumberRNAStrings(protein)
    print(numStrings)

