#!/usr/bin/python

""" Link : http://rosalind.info/problems/dna/ """

dna = 'TCTTTCGCCAAAGCCATTGTTGACCGCCAAAAGGTGTTTCGCAAACATCACACTGGTGGTTTTTCTCGACACTCACGTCAGCAGCGCCAATATCCGCATGTCTGGCGGTCATCGACACTACCACGGGACAGCAGTTAAGCTGAGTTCACACAACGTTTAGTATGACTTGCCACCATCTTACCAATGTGTACCATCTAGGGAAGAGGTCCGTTTGCCTCCTATGCCCGCAGGGACCAAATCAGTCATTGGTAAATAGCAATTCTACTCGGTAACAGGCTTCGGAGGGTTCCTACTACTACTTGCCTTTACTCCTGCAATGACGCACGCAACTTCATCAAAAGAAATAACAATAAGATTTGTGTCGATTGGGCGATGCTCGTGTAGTCCGCGTAATTGCTTGATCGCACGGCTACCTGCAAAGTCTAACACGATCAACGTATCCCGTGTCCTAGGTTGTCCGAGTTGCCTTTATTCTGGTCCCCTAAGCGCCCCGGTCGAGATTTACCGAGTTTAGAAGAATGTGCGGGTCCAATGAGTTGCCCTACCATAAGATTGGACCCAAGGGAACTTACGCCGATTATTGTCTAGAGGGTCACGTGCTTACCGAATCTTGTACGGCTGAGATTAAACCACATACAGGCCTGTACCCTCCAAGTTCGAGCATCCGCTACATCTCAGTGAGATGAATAGACCCGGGTCCAAGCCCGTGCATTGTACCATGAACGGGGGGTGCATTTATGTTGTCTAATTCGCGTTGGCCACCAGGCGCTTGGACACACAGCGGACCACAACTTTGTTATGTTTAGTTAGCGTTCGTCGTATCAGACCGGGCGGTAAAGATACGCTGGGTAGTACGCAATCTGAATTTAGGCTCGGCCCATC'

def countNucleotides(dna):
    counts = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    for base in dna:
        counts[base] += 1
    return counts

if __name__ == "__main__":
    counts = countNucleotides(dna)
    print(counts)

