#!/usr/bin/python

""" Link: http://rosalind.info/problems/subs/"""

string = 'AAAAAGGGTTCATGTGGGGTTCAGGGGTTCACGGGTTCAAGTGCGGGGTTCATGGGTTCACCCCTTTACTGGTAAGGGTTCAACTCGGGTTCACGGGTTCAAGGGTTCAAGGGTTCAGGGTTCAGGGTTCAGGGTTCAGTCGTGGGTTCACAAGGCGGGTTCAGGGGTTCAGGGTTCATGGGTTCAAGATCTTTGGGTTCATGGCAGGGTTCACGGGTTCATGTGGGGGTTCACGGGTTCAATACCAACTAGGGTTCACGCGGGGTTCATGTCCAGTAGGGAGGGTTCAGGGTTCAGGGTTCAAAGGGTTCATGTGGGGTTCATCGGGTTCAGGGTTCAAGAGGGTTCATGCCGGGTTCAGTATGGGTTCAGGGTTCACGGGTTCAGGGTTCAGAAGGGTTCAGGGTTCATGGGTTCATCAGCCTCGGGTTCAGGGTTCACTGTGGGTTCAAGATCGGGTTCATTGGGTTCAATATCGGGTTCAGGGTTCAGGGCTCAGGGTTCAGGGGTTCACTGGGTTCAGGGTTCACGGGTTCATGGGTTCAGGGTTCATAGGGTTCACCTGTCGGGTTCAGGGGTTCAGGGGTTCAGGGTTCATCGGGTTCAGAACTGAGGGTTCAGGGTTCAATGGGTTCAGGGTTCACAGGGTTCAGGGTTCAAGGGGTTCATGGTCGGGGTTCAGGGTTCAGAAGGGTTCATCGCGGGTTCAGGGTTCAGCGTCGAGGGTTCACAGCACGGGTTCAGTAAACCGGGTTCAGGGTTCATGTGAGGGTTCACTGGGTTCAGGGTTCAAGGGTTCAAGGGTTCACGGGGTTCAGGGTTCAGGGTTCAGGGTTCAGGGTTCAAAGGGTTCAAAGGGTTCAATGGGTTCACACAGCGGGTTCATCGCCATTAGGGTTCAGTCCGGGTTCATATCCGTCAGGGGTTCAGGGTTCAGGGTTCAGGGTTCATCGGGTTCAGGGTTCACATCTGGGTTCACGGGTTCA'
substring = 'GGGTTCAGG'

def getSubtringPositions(string, substring):
    list_pos = []
    string_len = len(string)
    substring_len = len(substring)
    for i in range(0, string_len - substring_len + 1):
        if string[i: i+substring_len] == substring:
            list_pos.append(i + 1)
    return list_pos

def printList(my_list):
    for item in my_list:
        print(item, end =' ')

if __name__ == "__main__":
    list_pos = getSubtringPositions(string, substring)
    #  print(list_pos)
    printList(list_pos)

