#!/usr/bin/python

""" Link: http://rosalind.info/problems/revc/ """

dna ='GACTCTGATATGACTCTAGGACATATGCCATGTAGTAATTGAGTCAAATGAGCGGTTAAACCGTTATGATATAAAAACGCCTAGAACAGCTAGAATCCGATCCACATTTTGCCAGCCGAAAAAAACTTACTGGTCGAGAGGAGCTAGCTACAGGGGGGCATCGACTACTATAGACTAGTCGCATAGCCGTGCCATACAAGATCCGACCATAATTGAGTAAATCGAATCGGGACTGACGCTTCTAAAAGTAGTGAATGCTGGACATAGCGGGTTGGGGGTGTGAATATGATCTAGACCTCCTACTCGGAAGATCTAGGCTCTGCATACGAAGGGCTATCGGTTTTCACCTGTACGCGTTGAATTACCTTTTAGTTTGCCGCGGGTTCAACGTCCGCTGAGCACGATAGGTCTCCTGATGATAGGTACCCCCGTACTCGTTGGTACGACAGTAGCGGCCCGAGCGTAACAGGTGCTCAACAAGACACATCCATACAATAGTTCCCAATGCCTACCGTCTAAGCTCGTATCGGCGGCGTCTGCCGGTGTGTTAAACAGCTTTACAGGCTTCTTATCAAGGAGATTGCACCCTCAATGTCATGATTGGCCAACATTCTGGTGCGCTAGACAGGCCATCTAGTGTCCAGCTGTCTTCCAAGTCCCCACATCGTGCCTGCGTTCTTTACACCGCGTTGGTAGTCGATCGTGCAATCGACTTTGAATATATTAGGCCTTAGAGCTGGAGCCCACTCGTTGAACCAAACATCATCAAGCCGACAACGTCTCAACAGATTAGATTATAATCTGTGGGAGCGGGAGGTGCGACGCTCTATATGGCCTTTCTCATGAGCGTGGCGCAGTCCCACTGCGGCCGTCCTTGTACTGAGATATTGGTCCCCTGGTGCTATA' 

reverse = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}

def getReverseComplement(dna):
    complement = ''
    for base in dna:
        complement += reverse[base]
    return complement[::-1]

def getReverseComplement2(dna):
    return ''.join([reverse[base] for base in dna])[::-1]

if __name__ =="__main__":
    reverse_complement = getReverseComplement2(dna)
    print(reverse_complement)
